    export const players = [
  {
    id: 1,
    name: "Gordon Anthony",
    goals: 2,
    assists: 0,
    shootsOnTarget: 12,
    yellowCard: 4,
    redCard: 0,
  },
  {
    id: 2,
    name: "Coady Conor",
    goals: 1,
    assists: 1,
    shootsOnTarget: 1,
    yellowCard: 1,
    redCard: 0,
  },
  {
    id: 3,
    name: "Gray Demarai",
    goals: 1,
    assists: 0,
    shootsOnTarget: 8,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 4,
    name: "Maupay Neal",
    goals: 1,
    assists: 0,
    shootsOnTarget: 2,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 5,
    name: "McNeil Dwight",
    goals: 1,
    assists: 0,
    shootsOnTarget: 2,
    yellowCard: 1,
    redCard: 0,
  }, {
    id: 21,
    name: "Alli Dele",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 6,
    name: "Begovic Asmir",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 7,
    name: "Coleman Seamus",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 8,
    name: "Davies Tom",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 2,
    redCard: 0,
  },
  {
    id: 9,
    name: "Doucoure Abdoulaye",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 10,
    name: "Godfrey Ben",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 11,
    name: "Gueye Idrissa",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 1,
    redCard: 0,
  },
  {
    id: 12,
    name: "Holgate Mason",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 1,
    redCard: 0,
  },
  {
    id: 13,
    name: "Iwobi Alex",
    goals: 0,
    assists: 3,
    shootsOnTarget: 1,
    yellowCard: 1,
    redCard: 0,
  },
  {
    id: 14,
    name: "Keane Michael",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 15,
    name: "Mina Yerry",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 1,
    redCard: 0,
  }, {
    id: 11,
    name: "Mykolenko Vitaliy",
    goals: 0,
    assists: 0,
    shootsOnTarget: 1,
    yellowCard: 1,
    redCard: 0,
  },
  {
    id: 16,
    name: "Onana Amadou Mvom",
    goals: 0,
    assists: 1,
    shootsOnTarget: 0,
    yellowCard: 2,
    redCard: 0,
  },
  {
    id: 17,
    name: "Pickford Jordan",
    goals: 0,
    assists: 1,
    shootsOnTarget: 0,
    yellowCard: 3,
    redCard: 0,
  },
  {
    id: 18,
    name: "Rondon Salomon",
    goals: 0,
    assists: 0,
    shootsOnTarget: 0,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 19,
    name: "Tarkowski James",
    goals: 0,
    assists: 0,
    shootsOnTarget: 2,
    yellowCard: 0,
    redCard: 0,
  },
  {
    id: 20,
    name: "Patterson Nathan",
    goals: 0,
    assists: 0,
    shootsOnTarget: 1,
    yellowCard: 1,
    redCard: 0,
  }
]
