
export const teams = [
    {
      teamId: 1,
      name: "Tottenham Hotspur",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8586.png",
      played: 7,
      wins: 5,
      draws: 2,
      losses: 0,
      goalsFor: 18,
      goalsAgains: 7,
      goalsDiff: 11,
      points: 17,
      playedHome: 4,
      playedAway: 3,
      winsAway: 1,
      drawsAway: 2,
      lossesAway: 0,
      goalsForAway: 5,
      goalsAgainsAway: 3,
      goalsDiffAway: 2,
      pointsAway: 5,
      winsHome: 4,
      drawsHome: 0,
      lossesHome: 0,
      goalsForHome: 13,
      goalsAgainsHome: 4,
      goalsDiffHome: 9,
      pointsHome: 12,
    },
    {
      teamId: 2,
      name: "Arsenal",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/9825.png",
      played: 7,
      wins: 6,
      draws: 0,
      losses: 1,
      goalsFor: 17,
      goalsAgains: 7,
      goalsDiff: 10,
      points: 18,
      playedAway: 4,
      winsAway: 3,
      drawsAway: 0,
      lossesAway: 1,
      goalsForAway: 9,
      goalsAgainsAway: 3,
      goalsDiffAway: 6,
      pointsAway: 9,
      playedHome: 3,
      winsHome: 3,
      drawsHome: 0,
      lossesHome: 0,
      goalsForHome: 8,
      goalsAgainsHome: 4,
      goalsDiffHome: 4,
      pointsHome: 9,
    },
    {
      teamId: 3,
      name: "Manchester City",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8456.png",
      played: 7,
      wins: 5,
      draws: 2,
      losses: 0,
      goalsFor: 23,
      goalsAgains: 6,
      goalsDiff: 17,
      points: 17,
      playedAway: 4,
      winsAway: 2,
      drawsAway: 2,
      lossesAway: 0,
      goalsForAway: 9,
      goalsAgainsAway: 4,
      goalsDiffAway: 5,
      pointsAway: 8,
      playedHome: 3,
      winsHome: 3,
      drawsHome: 0,
      lossesHome: 0,
      goalsForHome: 14,
      goalsAgainsHome: 2,
      goalsDiffHome: 12,
      pointsHome: 9,
    },
    {
      teamId: 4,
      name: "Brighton & Hove Albion",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/10204.png",
      played: 6,
      wins: 4,
      draws: 1,
      losses: 1,
      goalsFor: 11,
      goalsAgains: 5,
      goalsDiff: 6,
      points: 13,
      playedAway: 3,
      winsAway: 2,
      drawsAway: 0,
      lossesAway: 1,
      goalsForAway: 5,
      goalsAgainsAway: 3,
      goalsDiffAway: 2,
      pointsAway: 6,
      playedHome: 3,
      winsHome: 2,
      drawsHome: 1,
      lossesHome: 0,
      goalsForHome: 6,
      goalsAgainsHome: 2,
      goalsDiffHome: 4,
      pointsHome: 7,
    },
    {
      teamId: 5,
      name: "Manchester United",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/10260.png",
      played: 6,
      wins: 4,
      draws: 0,
      losses: 2,
      goalsFor: 8,
      goalsAgains: 8,
      goalsDiff: 0,
      points: 12,
      playedAway: 3,
      winsAway: 2,
      drawsAway: 0,
      lossesAway: 1,
      goalsForAway: 2,
      goalsAgainsAway: 4,
      goalsDiffAway: -2,
      pointsAway: 6,
      playedHome: 3,
      winsHome: 2,
      drawsHome: 0,
      lossesHome: 1,
      goalsForHome: 6,
      goalsAgainsHome: 4,
      goalsDiffHome: 2,
      pointsHome: 6,
    },
    {
      teamId: 6,
      name: "Fulham",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/9879.png",
      played: 7,
      wins: 3,
      draws: 2,
      losses: 2,
      goalsFor: 12,
      goalsAgains: 11,
      goalsDiff: 1,
      points: 11,
      playedAway: 4,
      winsAway: 1,
      drawsAway: 1,
      lossesAway: 2,
      goalsForAway: 5,
      goalsAgainsAway: 6,
      goalsDiffAway: -1,
      pointsAway: 4,
      playedHome: 3,
      winsHome: 2,
      drawsHome: 1,
      lossesHome: 0,
      goalsForHome: 7,
      goalsAgainsHome: 5,
      goalsDiffHome: 2,
      pointsHome: 7,
    },
    {
      teamId: 7,
      name: "Chelsea",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8455.png",
      played: 6,
      wins: 3,
      draws: 1,
      losses: 2,
      goalsFor: 8,
      goalsAgains: 9,
      goalsDiff: -1,
      points: 10,
      playedAway: 3,
      winsAway: 1,
      drawsAway: 0,
      lossesAway: 2,
      goalsForAway: 2,
      goalsAgainsAway: 5,
      goalsDiffAway: -3,
      pointsAway: 3,
      playedHome: 3,
      winsHome: 2,
      drawsHome: 1,
      lossesHome: 0,
      goalsForHome: 6,
      goalsAgainsHome: 4,
      goalsDiffHome: 2,
      pointsHome: 7,
    },
    {
      teamId: 8,
      name: "Liverpool",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8650.png",
      played: 6,
      wins: 2,
      draws: 3,
      losses: 1,
      goalsFor: 15,
      goalsAgains: 6,
      goalsDiff: 9,
      points: 9,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 2,
      lossesAway: 1,
      goalsForAway: 3,
      goalsAgainsAway: 4,
      goalsDiffAway: -1,
      pointsAway: 2,
      playedHome: 3,
      winsHome: 2,
      drawsHome: 1,
      lossesHome: 0,
      goalsForHome: 12,
      goalsAgainsHome: 2,
      goalsDiffHome: 10,
      pointsHome: 7,
    },
    {
      teamId: 9,
      name: "Brentford",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/9937.png",
      played: 7,
      wins: 2,
      draws: 3,
      losses: 2,
      goalsFor: 15,
      goalsAgains: 12,
      goalsDiff: 3,
      points: 9,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 2,
      lossesAway: 1,
      goalsForAway: 5,
      goalsAgainsAway: 6,
      goalsDiffAway: -1,
      pointsAway: 2,
      playedHome: 4,
      winsHome: 2,
      drawsHome: 1,
      lossesHome: 1,
      goalsForHome: 10,
      goalsAgainsHome: 6,
      goalsDiffHome: 4,
      pointsHome: 7,
    },
    {
      teamId: 10,
      name: "Newcastle United",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/10261.png",
      played: 7,
      wins: 1,
      draws: 5,
      losses: 1,
      goalsFor: 8,
      goalsAgains: 7,
      goalsDiff: 1,
      points: 8,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 2,
      lossesAway: 1,
      goalsForAway: 2,
      goalsAgainsAway: 3,
      goalsDiffAway: -1,
      pointsAway: 2,
      playedHome: 4,
      winsHome: 1,
      drawsHome: 3,
      lossesHome: 0,
      goalsForHome: 6,
      goalsAgainsHome: 3,
      goalsDiffHome: 2,
      pointsHome: 6,
    },
    {
      teamId: 11,
      name: "Leeds United",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8463.png",
      played: 6,
      wins: 2,
      draws: 2,
      losses: 2,
      goalsFor: 10,
      goalsAgains: 10,
      goalsDiff: 0,
      points: 8,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 1,
      lossesAway: 2,
      goalsForAway: 4,
      goalsAgainsAway: 8,
      goalsDiffAway: -4,
      pointsAway: 1,
      playedHome: 3,
      winsHome: 2,
      drawsHome: 1,
      lossesHome: 0,
      goalsForHome: 6,
      goalsAgainsHome: 2,
      goalsDiffHome: 4,
      pointsHome: 7,
    },
    {
      teamId: 12,
      name: "AFC Bournemouth",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8678.png",
      played: 7,
      wins: 2,
      draws: 2,
      losses: 3,
      goalsFor: 6,
      goalsAgains: 19,
      goalsDiff: -13,
      points: 8,
      playedAway: 4,
      winsAway: 1,
      drawsAway: 1,
      lossesAway: 2,
      goalsForAway: 4,
      goalsAgainsAway: 16,
      goalsDiffAway: -12,
      pointsAway: 4,
      playedHome: 3,
      winsHome: 1,
      drawsHome: 1,
      lossesHome: 1,
      goalsForHome: 2,
      goalsAgainsHome: 3,
      goalsDiffHome: -1,
      pointsHome: 4,
    },
    {
      teamId: 13,
      name: "Everton",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8668.png",
      played: 7,
      wins: 1,
      draws: 4,
      losses: 2,
      goalsFor: 5,
      goalsAgains: 6,
      goalsDiff: -1,
      points: 7,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 2,
      lossesAway: 1,
      goalsForAway: 3,
      goalsAgainsAway: 4,
      goalsDiffAway: -1,
      pointsAway: 2,
      playedHome: 4,
      winsHome: 1,
      drawsHome: 2,
      lossesHome: 1,
      goalsForHome: 2,
      goalsAgainsHome: 2,
      goalsDiffHome: 0,
      pointsHome: 5,
    },
    {
      teamId: 14,
      name: "Wolverhampton Wanderers",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8602.png",
      played: 7,
      wins: 1,
      draws: 3,
      losses: 3,
      goalsFor: 3,
      goalsAgains: 7,
      goalsDiff: -4,
      points: 6,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 1,
      lossesAway: 2,
      goalsForAway: 1,
      goalsAgainsAway: 3,
      goalsDiffAway: -2,
      pointsAway: 1,
      playedHome: 4,
      winsHome: 1,
      drawsHome: 2,
      lossesHome: 1,
      goalsForHome: 2,
      goalsAgainsHome: 4,
      goalsDiffHome: -2,
      pointsHome: 5,
    },
    {
      teamId: 15,
      name: "Southampton",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8466.png",
      played: 7,
      wins: 2,
      draws: 1,
      losses: 4,
      goalsFor: 7,
      goalsAgains: 11,
      goalsDiff: -4,
      points: 7,
      playedAway: 4,
      winsAway: 1,
      drawsAway: 0,
      lossesAway: 3,
      goalsForAway: 3,
      goalsAgainsAway: 7,
      goalsDiffAway: -4,
      pointsAway: 3,
      playedHome: 3,
      winsHome: 1,
      drawsHome: 1,
      lossesHome: 1,
      goalsForHome: 4,
      goalsAgainsHome: 4,
      goalsDiffHome: 0,
      pointsHome: 4,
    },
    {
      teamId: 16,
      name: "Aston Villa",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/10252.png",
      played: 7,
      wins: 2,
      draws: 1,
      losses: 4,
      goalsFor: 6,
      goalsAgains: 10,
      goalsDiff: -4,
      points: 7,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 0,
      lossesAway: 3,
      goalsForAway: 2,
      goalsAgainsAway: 7,
      goalsDiffAway: -5,
      pointsAway: 0,
      playedHome: 4,
      winsHome: 2,
      drawsHome: 1,
      lossesHome: 1,
      goalsForHome: 4,
      goalsAgainsHome: 3,
      goalsDiffHome: 1,
      pointsHome: 7,
    },
    {
      teamId: 17,
      name: "Crystal Palace",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/9826.png",
      played: 6,
      wins: 1,
      draws: 3,
      losses: 2,
      goalsFor: 7,
      goalsAgains: 9,
      goalsDiff: -2,
      points: 6,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 2,
      lossesAway: 1,
      goalsForAway: 3,
      goalsAgainsAway: 5,
      goalsDiffAway: -2,
      pointsAway: 2,
      playedHome: 3,
      winsHome: 1,
      drawsHome: 1,
      lossesHome: 1,
      goalsForHome: 4,
      goalsAgainsHome: 4,
      goalsDiffHome: 0,
      pointsHome: 4,
    },
    {
      teamId: 18,
      name: "West Ham United",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8654.png",
      played: 7,
      wins: 1,
      draws: 1,
      losses: 5,
      goalsFor: 3,
      goalsAgains: 9,
      goalsDiff: -6,
      points: 4,
      playedAway: 4,
      winsAway: 1,
      drawsAway: 0,
      lossesAway: 3,
      goalsForAway: 2,
      goalsAgainsAway: 4,
      goalsDiffAway: -2,
      pointsAway: 3,
      playedHome: 3,
      winsHome: 0,
      drawsHome: 1,
      lossesHome: 2,
      goalsForHome: 1,
      goalsAgainsHome: 5,
      goalsDiffHome: -4,
      pointsHome: 1,
    },
    {
      teamId: 19,
      name: "Nottingham Forest",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/10203.png",
      played: 7,
      wins: 1,
      draws: 1,
      losses: 5,
      goalsFor: 6,
      goalsAgains: 17,
      goalsDiff: -11,
      points: 4,
      playedAway: 3,
      winsAway: 0,
      drawsAway: 1,
      lossesAway: 2,
      goalsForAway: 1,
      goalsAgainsAway: 9,
      goalsDiffAway: -8,
      pointsAway: 1,
      playedHome: 4,
      winsHome: 1,
      drawsHome: 0,
      lossesHome: 3,
      goalsForHome: 5,
      goalsAgainsHome: 8,
      goalsDiffHome: -3,
      pointsHome: 3,
    },
    {
      teamId: 20,
      name: "Leicester City",
      flag: "https://lsm-static-prod.livescore.com/medium/enet/8197.png",
      played: 7,
      wins: 0,
      draws: 1,
      losses: 6,
      goalsFor: 10,
      goalsAgains: 22,
      goalsDiff: -12,
      points: 1,
      playedAway: 4,
      winsAway: 0,
      drawsAway: 0,
      lossesAway: 4,
      goalsForAway: 7,
      goalsAgainsAway: 17,
      goalsDiffAway: -10,
      pointsAway: 0,
      playedHome: 3,
      winsHome: 0,
      drawsHome: 1,
      lossesHome: 2,
      goalsForHome: 3,
      goalsAgainsHome: 5,
      goalsDiffHome: -2,
      pointsHome: 1,
    },
  ]
  
  